### PR TITLE
Added contentlayout to all relevant pages 

### PR DESCRIPTION
**Pull request by eevanwong**
Didnt delete prof page b/c i added a bit of styling to the main profile page so that the items were vertically aligned. The rest of the code changes is with the graph stuff that happened last night.

### CODE REVIEW

**Review by parminpatel28 — COMMENTED** [review]
You have merge conflicts that can be resolved with rebase.

**Comment by shivam-sh** [comment]
What exactly is this PR for? I see a lot of js files for graphs, but I don’t think that’s how we’re going to be structuring the files?

**Comment by parminpatel28** [comment]
> What exactly is this PR for? I see a lot of js files for graphs, but I don’t think that’s how we’re going to be structuring the files?

It needs to be rebased with the current branch.

**Comment by eevanwong** [comment]
the pr is specifically for the baselayout, the thing is that this also includes all the grpahs that were added (from parmins branch).

**Comment by eevanwong** [comment]
image
im getting this tho

**Comment by shivam-sh** [comment]
Okay I think this’ll be fine after a rebase, but restructuring this to be something more like
`import { Content } from "../../../components/layout/layout"`
Would probably be a cleaner approach, this way the `<Content>` component would describe its own function right where it’s being imported, and we could also add more layout based components to the `"../../../components/layout/layout"` file as we need to add more.
Might help keep our project cleaner

**Comment by eevanwong** [comment]
its renamed @shivam-sh

**Comment by shivam-sh** [comment]
Looks good, I think we can make the `export default function Layout...` into `export function Content...` when we add more stuff, but for now it should be fine.

If you want help with the rebase I can go ahead and do that for you

**Comment by eevanwong** [comment]
nah i already rebased so it should be ok

**Comment by eevanwong** [comment]
i left it at export default cuz only one fn so ye its ok for now

**Review by eevanwong — COMMENTED** [review]
goddamn

**Review by shivam-sh — APPROVED** [review]

**Pull request merged**
